### ISSUE TITLE
Time is not fully replaceable as number

### ISSUE THREAD

**Issue by amoshydra** [amoshydra/time-chainer#10]
Current implementation will fail type check

```js
typeof Time.days(30) !== 'number'
```

This cause undesirable effect when used like this

```js
jest.advanceTimersByTime(Time.days(30));
```

as the function above will cause sinon to throw error 

```
TypeError: str.split is not a function
      at parseTime (node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:92:27)
      at doTick (node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:853:23)
      at Object.tick (node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:989:20)
      at FakeTimers.advanceTimersByTime (node_modules/@jest/fake-timers/build/modernFakeTimers.js:10
```

https://github.com/sinonjs/fake-timers/blob/v6.0.1/src/fake-timers-src.js#L851-L853

**Comment by amoshydra** [comment]
Update documentation to provide a workaround for this #23
